const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rm=n=>'RM '+(n/100).toFixed(2);let data;
function status(s){$('#status').textContent=s;}
async function refresh(){data=await ShopAPI.rpc('admin_dashboard',{},true);render();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;status('Signing in…');try{await ShopAPI.login(e.target.email.value,e.target.password.value);e.target.password.value='';await refresh();$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;status('');}catch(err){status(err.message);}finally{b.disabled=false;}};
$('#logout').onclick=async()=>{await ShopAPI.logout();location.reload();};
$('#refresh').onclick=()=>run(refresh);
async function run(fn){try{status('Saving…');await fn();status('Updated.');}catch(e){status(e.message);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{for(const id of ['orders','inventory','settings'])$('#'+id).hidden=id!==b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));});document.querySelector('[data-tab="orders"]').setAttribute('aria-selected','true');
function render(){const orders=data.orders;$('#metrics').innerHTML=`<div class="metric">Pending (latest 200)<strong>${orders.filter(o=>o.status==='pending').length}</strong></div><div class="metric">Paid / shipped<strong>${orders.filter(o=>['paid','shipped'].includes(o.status)).length}</strong></div><div class="metric">Unsold units<strong>${data.variants.reduce((n,v)=>n+v.stock,0)}</strong></div>`;
 renderOrders();$('#variantList').innerHTML=data.variants.map(v=>`<form class="variant" data-id="${esc(v.id)}"><strong>${esc(v.color)} / ${esc(v.size)}</strong><label>Price (RM)<input name="price" type="number" min="1" max="10000" step="0.01" value="${v.price_sen==null?'':v.price_sen/100}"></label><label>Stock<input name="stock" type="number" min="0" max="100000" step="1" required value="${v.stock}"></label><label class="check"><input name="active" type="checkbox" ${v.active?'checked':''}> Active</label><button>Save</button></form>`).join('');
 document.querySelectorAll('.variant').forEach(f=>f.onsubmit=e=>{e.preventDefault();run(async()=>{await ShopAPI.rpc('admin_save_variant',{p_id:f.dataset.id,p_price:f.price.value===''?null:Math.round(Number(f.price.value)*100),p_stock:Number(f.stock.value),p_active:f.active.checked},true);await refresh();});});
 const f=$('#settingsForm'),s=data.settings;f.whatsapp.value=s.whatsapp;f.shipping.value=s.shipping_sen==null?'':s.shipping_sen/100;f.launch.value=new Date(Date.parse(s.launch_at)+8*3600000).toISOString().slice(0,16);f.open.checked=s.orders_open;
}
function renderOrders(){const orders=data.orders.filter(o=>$('#filter').value==='all'||($('#filter').value==='verification'?o.status==='pending'&&o.payment_reported_at:o.status===$('#filter').value));$('#orderList').innerHTML=orders.length?orders.map(o=>`<article class="order"><h3>${esc(o.reference)} · ${esc(o.status)}${o.payment_review?' · PAYMENT REVIEW':''}</h3><p>${esc(o.customer_name)} · ${esc(o.phone)} · ${esc(o.email)}<br>${esc(new Date(o.created_at).toLocaleString())}</p><address>${esc(o.address)}</address><ul>${o.items.map(i=>`<li>${esc(i.color)} / ${esc(i.size)} × ${i.quantity} — ${rm(i.unit_price_sen*i.quantity)}</li>`).join('')}</ul><strong>${rm(o.subtotal_sen+o.shipping_sen)} including shipping</strong><p>${o.status==='pending'?'Reservation ends '+esc(new Date(o.expires_at).toLocaleString()):esc(o.tracking||'')}</p><p>${o.payment_reported_at?'Customer reported payment at '+esc(new Date(o.payment_reported_at).toLocaleString()):'Payment not reported by customer'}</p><p>Email: ${esc(Object.entries(o.emails||{}).map(([kind,state])=>kind+': '+state).join(' · ')||'Not queued')}</p><div class="actions">${o.payment_method==='bank_transfer'&&['pending','paid','shipped'].includes(o.status)?`<button data-email="${o.id}">Send / retry order email</button>`:''}${o.payment_method==='bank_transfer'&&['pending','expired'].includes(o.status)?`<button data-confirm-bank="${o.id}">Verify bank payment</button>`:''}${o.status==='pending'?`<button data-id="${o.id}" data-state="cancelled">Cancel reservation</button>`:o.status==='paid'?`<button data-id="${o.id}" data-state="shipped">Mark shipped</button>`:''}</div></article>`).join(''):'<p>No orders with this status.</p>';
 document.querySelectorAll('[data-email]').forEach(b=>b.onclick=()=>{b.disabled=true;run(async()=>{const result=await ShopAPI.adminPayment({action:'email',order_id:b.dataset.email});await refresh();alert('Email status: '+result.email);}).finally(()=>{b.disabled=false;});});
 document.querySelectorAll('[data-confirm-bank]').forEach(b=>b.onclick=()=>{if(!confirm('Check your bank account first. Has the full amount actually arrived? A customer clicking paid is not proof.'))return;const reference=prompt('Actual bank transaction reference (not the order number):');if(!reference)return;const amount=prompt('Amount received in RM:');if(!amount||!/^\d+(\.\d{1,2})?$/.test(amount)){status('Enter the exact amount received, e.g. 97.00');return}b.disabled=true;run(async()=>{const result=await ShopAPI.adminPayment({action:'confirm',order_id:b.dataset.confirmBank,bank_reference:reference.trim(),amount_sen:Math.round(Number(amount)*100)});await refresh();if(result.status==='review')alert('Payment recorded, but stock is no longer available. Arrange a refund or fulfilment manually before shipping.');}).finally(()=>{b.disabled=false;});});
 document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{const next=b.dataset.state;let tracking='';if(next==='paid'&&!confirm('Have you verified the full payment in your bank account? This will deduct stock.'))return;if(next==='cancelled'&&!confirm('Cancel this unpaid reservation and release its stock?'))return;if(next==='shipped'){tracking=prompt('Courier and tracking number');if(!tracking)return;}b.disabled=true;run(async()=>{await ShopAPI.rpc('admin_order_status',{p_id:b.dataset.id,p_status:next,p_tracking:tracking},true);await refresh();}).finally(()=>{b.disabled=false;});});
}
$('#filter').onchange=renderOrders;
$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=e.target;run(async()=>{await ShopAPI.rpc('admin_save_settings',{p_open:f.open.checked,p_launch:f.launch.value+':00+08:00',p_whatsapp:f.whatsapp.value.trim(),p_shipping:f.shipping.value===''?null:Math.round(Number(f.shipping.value)*100)},true);await refresh();});};
if(!ShopAPI.configured){status('Backend setup is required. Follow BACKEND-SETUP.md, then enter the public connection details in shop-config.js.');$('#loginForm button').disabled=true;}
