const products=[{id:'barrel-charcoal',name:'Pelikat-Inspired Trousers',color:'Charcoal',price:null,image:'assets/charcoal.jpg',description:'A loose barrel silhouette with a gathered waistband and cuffs, finished with all-over geometric motifs. Fabric composition and measurements will be confirmed before launch.'},{id:'barrel-burgundy',name:'Pelikat-Inspired Trousers',color:'Burgundy',price:null,image:'assets/burgundy.jpg',description:'A loose barrel silhouette with a gathered waistband and cuffs, finished with all-over geometric motifs. Fabric composition and measurements will be confirmed before launch.'},{id:'barrel-slate',name:'Pelikat-Inspired Trousers',color:'Slate blue',price:null,image:'assets/slate.jpg',description:'A loose barrel silhouette with a gathered waistband and cuffs, finished with all-over geometric motifs. Fabric composition and measurements will be confirmed before launch.'}];
products.forEach(p=>{p.alternate=p.image.replace('.jpg','-alternate.jpg');p.campaign=p.image.replace('.jpg','-pelikat.png')});
const sizes=['S','M','L','XL'];const money=n=>n===null?'Price to be announced':'RM '+n.toFixed(2);let cart=[];let selectedSize=null;let timer;const pd=document.querySelector('#productDialog'),cd=document.querySelector('#cartDialog');
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('#products').innerHTML=products.map(p=>`<article class="product-card"><div class="product-image"><button class="product-photo" data-product="${p.id}" aria-label="View ${p.color} trousers"><img class="campaign-poster" src="${p.campaign}" alt="${p.color} pelikat-inspired pants editorial campaign" loading="lazy"><img class="alternate-photo" src="${p.alternate}" alt="${p.color} alternate view" loading="lazy"></button><span class="product-tag">COMING SOON</span></div><div class="card-views" role="group" aria-label="${p.color} photo views"><button data-card-view="0" aria-pressed="true">01 / Campaign</button><button data-card-view="1" aria-pressed="false">02 / Product</button></div><button class="product-title" data-product="${p.id}"><div class="product-info"><h3>${p.name}</h3><span>${money(p.price)}</span></div><p class="product-color">${p.color} <span aria-hidden="true">↗</span></p></button></article>`).join('');
document.querySelectorAll('[data-card-view]').forEach(b=>b.onclick=()=>{const card=b.closest('.product-card');card.classList.toggle('show-alternate',b.dataset.cardView==='1');card.querySelectorAll('[data-card-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
function openProduct(id){const p=products.find(p=>p.id===id);if(!p)return;selectedSize=null;document.querySelector('#productContent').innerHTML=`<div class="product-detail"><div class="detail-gallery"><button class="zoom-photo" aria-label="Zoom product photo" aria-pressed="false"><img class="detail-image" src="${p.image}" alt="${p.color} patterned barrel trousers"><span>Tap to zoom +</span></button><div class="gallery-thumbs">${[p.image,p.alternate].map((src,i)=>`<button data-gallery="${src}" aria-label="View photo ${i+1}" aria-pressed="${i===0}"><img src="${src}" alt="">${i===0?"Front":"Alternate"}</button>`).join('')}</div></div><div class="detail-copy"><div class="eyebrow">THE FIRST DROP / COMING SOON</div><h2>${p.name}</h2><p>${money(p.price)} <span class="muted">· ${p.color}</span></p><p>${p.description}</p><p id="sizeLabel">Preview sizes — range to be confirmed</p><div class="sizes" role="group" aria-labelledby="sizeLabel">${sizes.map(s=>`<button data-size="${s}" aria-pressed="false">${s}</button>`).join('')}</div><button class="button" id="addButton">Select a size <span>+</span></button><p class="sample-note">Preview only. Product photos show the upcoming drop. Names and size options are provisional; prices are not yet confirmed. Adding to your bag does not reserve stock or place an order.</p></div></div>`;document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelector('#addButton').innerHTML='Add to demo bag <span>+</span>'});document.querySelector('#addButton').onclick=()=>{if(!selectedSize){document.querySelector('#sizeLabel').textContent='Please choose a size first';return}try{addToBag(id,selectedSize);pd.close();cd.showModal();notify('Added to your bag')}catch(e){notify(e.message)}};document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{document.querySelector('.detail-image').src=b.dataset.gallery;document.querySelectorAll('[data-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});const zoom=document.querySelector('.zoom-photo');zoom.onclick=()=>{const active=zoom.classList.toggle('zoomed');zoom.setAttribute('aria-pressed',String(active));zoom.querySelector('span').textContent=active?'Tap to zoom out −':'Tap to zoom +'};pd.showModal()}
function addToBag(id,size){if(!products.some(p=>p.id===id)||!sizes.includes(size))throw Error('Choose a valid product and size');const item=cart.find(i=>i.id===id&&i.size===size);if(item){if(item.qty>=10)throw Error('Maximum 10 per size');item.qty++}else cart.push({id,size,qty:1});renderCart();return {items:cart.map(x=>({...x})),total:null}}
function notify(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('toast-visible');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('toast-visible'),2500)}
function renderCart(){const count=cart.reduce((n,i)=>n+i.qty,0);document.querySelector('#bagCount').textContent=count;document.querySelector('#cartHeadingCount').textContent=count;document.querySelector('#cartItems').innerHTML=cart.length?cart.map((i,index)=>{const p=products.find(p=>p.id===i.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.color} / ${i.size}</p><p>${money(p.price===null?null:p.price*i.qty)}</p><div class="quantity-row"><div class="quantity"><button data-qty="${index}" data-change="-1" aria-label="Decrease ${p.name} quantity">−</button><span>${i.qty}</span><button data-qty="${index}" data-change="1" aria-label="Increase ${p.name} quantity" ${i.qty>=10?'disabled':''}>+</button></div><button class="remove" data-remove="${index}">Remove</button></div></div></div>`}).join(''):`<div class="empty"><h3>A fresh start.</h3><p>Your bag is empty.<br>Find your everyday favourite.</p><button class="button" id="continue">Explore collection ↗</button></div>`;document.querySelector('#cartBottom').innerHTML=cart.length?`<div class="total"><span>Subtotal</span><strong>${money(null)}</strong></div><button class="button checkout" disabled>Checkout coming soon</button><p class="cart-note">This is a store preview. Payments and orders are not available yet. Shipping will be confirmed before launch. Your demo bag resets when you reload.</p>`:'';document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.qty);cart[i].qty+=Number(b.dataset.change);if(cart[i].qty<=0)cart.splice(i,1);renderCart()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);renderCart()});const c=document.querySelector('#continue');if(c)c.onclick=()=>{cd.close();document.querySelector('#collection').scrollIntoView({behavior:'smooth'})}}
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product));document.querySelector('#bagButton').onclick=()=>cd.showModal();document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});renderCart();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_sample_to_bag',title:'Add sample product to bag',description:'Stage a sample apparel product in the demo bag. Does not reserve inventory, order or pay.',inputSchema:{type:'object',properties:{productId:{type:'string',enum:products.map(p=>p.id)},size:{type:'string',enum:sizes}},required:['productId','size'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({productId,size})=>addToBag(productId,size)})).catch(()=>{})}catch{}}
const menuDialog=document.querySelector('#menuDialog');document.querySelector('#menuButton').onclick=()=>menuDialog.showModal();menuDialog.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menuDialog.close()));
const hero=document.querySelector('.hero');let activeSlide=0;const slideColors=['CHARCOAL','BURGUNDY','SLATE BLUE'];function setSlide(index){if(!Number.isInteger(index)||index<0||index>=slideColors.length)throw Error('Invalid colourway');activeSlide=index;hero.dataset.color=['charcoal','burgundy','slate'][index];document.querySelector('#heroShop').textContent='EXPLORE '+slideColors[index]+' ↗';document.querySelectorAll('[data-visual]').forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-hidden',String(i!==index))});document.querySelectorAll('[data-slide]').forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-pressed',String(i===index))});document.querySelector('#heroColor').textContent=slideColors[index];document.querySelector('#slideStatus').textContent=`Colourway ${index+1} of ${slideColors.length}`;}
document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>setSlide(Number(b.dataset.slide)));document.querySelector('#nextSlide').onclick=()=>setSlide((activeSlide+1)%slideColors.length);let touchStart=null;document.querySelector('.campaign-image').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});document.querySelector('.campaign-image').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)setSlide((activeSlide+(dx<0?1:slideColors.length-1))%slideColors.length);touchStart=null},{passive:true});

document.querySelector('#heroShop').onclick=()=>openProduct(products[activeSlide].id);
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver' in window && !reducedMotion.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-top,.product-card,.story-copy,.motion-intro,.video-card').forEach(el=>{el.classList.add('reveal');observer.observe(el)});}
window.addEventListener('message',e=>{if(e.origin!=='https://www.tiktok.com'||!e.data||e.data['x-tiktok-player']!==true)return;const frames=[...document.querySelectorAll('.video-card iframe,.hero-film iframe')];const sender=frames.find(f=>f.contentWindow===e.source);if(!sender)return;if(e.data.type==='onStateChange'&&e.data.value===1)frames.filter(f=>f!==sender).forEach(f=>f.contentWindow.postMessage({'x-tiktok-player':true,type:'pause'},'https://www.tiktok.com'));});

// Fixed launch instant: October 7, 2026 at midnight in Malaysia (UTC+8).
const dropAt=Date.parse('2026-10-07T00:00:00+08:00');
function getDropTime(now){const remaining=Math.max(0,Math.floor((dropAt-now)/1000));return {days:Math.floor(remaining/86400),hours:Math.floor(remaining/3600)%24,minutes:Math.floor(remaining/60)%60,seconds:remaining%60,ended:now>=dropAt};}
function updateCountdown(){const t=getDropTime(Date.now());for(const unit of ['days','hours','minutes','seconds'])document.querySelector('#count'+unit[0].toUpperCase()+unit.slice(1)).textContent=String(t[unit]).padStart(2,'0');if(t.ended){document.querySelector('#dropStatus').textContent='The countdown has ended. Check back for drop availability.';clearInterval(countdownTimer);}}
let countdownTimer=setInterval(updateCountdown,1000);updateCountdown();
