import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {cents,validSignature,expiryMY} from '../server/store.js';
let db;
const customer={name:'Test Customer',email:'test@example.com',phone:'60123456789',address:'123 Test Street, 50000 Kuala Lumpur, Malaysia'};
const items=[{variant_id:'barrel-charcoal',quantity:1}];
const call=async(name,args=[])=>{const p=args.map((_,i)=>'$'+(i+1)).join(',');return(await db.query(`select ${name}(${p}) as result`,args)).rows[0].result};
const place=(id=randomUUID(),bag=items)=>call('place_order',[id,customer,bag]);
before(async()=>{
 db=new PGlite();
 await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$ select null::uuid $$;");
 for(const file of ['202610010001_store.sql','202610010002_payments.sql'])await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
 await db.exec("update shop_settings set orders_open=true,launch_at=now()-interval '1 day',shipping_sen=800;update variants set active=true,stock=10;");
});
after(async()=>{await db?.close()});
test('amount parsing rejects ambiguous or negative amounts',()=>{assert.equal(cents('89.00'),8900);assert.equal(cents('0.5'),50);for(const s of ['-1','1e3','89.001','NaN'])assert.throws(()=>cents(s))});
test('callback signature covers documented fields and rejects tampering',()=>{const b={status:'1',order_id:'IS-ABC',refno:'TP1'};b.hash=createHash('md5').update('secret1IS-ABCTP1ok').digest('hex');assert.equal(validSignature(b,'secret'),true);assert.equal(validSignature({...b,status:'3'},'secret'),false);assert.equal(validSignature({...b,hash:'bad'},'secret'),false)});
test('bill expiry is formatted in Malaysia time',()=>assert.equal(expiryMY('2026-10-02T12:00:00Z'),'02-10-2026 20:00:00'));
test('server calculates price, reserves stock and deduplicates retries',async()=>{const id=randomUUID();const first=await place(id);assert.equal(first.total_sen,9700);assert.equal((await place(id)).reference,first.reference);assert.equal((await db.query('select count(*)::int n from orders where request_id=$1',[id])).rows[0].n,1);await assert.rejects(()=>place(id,[{variant_id:'barrel-charcoal',quantity:2}]),/Request already used/)});
test('overselling and invalid quantities are rejected',async()=>{await assert.rejects(()=>place(randomUUID(),[{variant_id:'barrel-charcoal',quantity:10}]),/enough stock/);await assert.rejects(()=>place(randomUUID(),[{variant_id:'barrel-charcoal',quantity:0}]),/Invalid quantity/)});
test('payment claim is single-use; duplicate callback deducts stock once',async()=>{const id=randomUUID(),o=await place(id);assert.equal((await call('checkout_claim',[id])).claimed,true);assert.equal((await call('checkout_claim',[id])).claimed,false);await call('checkout_attach',[id,'testbill1']);const stock=(await db.query("select stock from variants where id='barrel-charcoal'")).rows[0].stock;await call('confirm_payment',[o.reference,'testbill1','invoice1',9700]);await call('confirm_payment',[o.reference,'testbill1','invoice1',9700]);assert.equal((await db.query("select stock from variants where id='barrel-charcoal'")).rows[0].stock,stock-1);assert.equal((await call('checkout_status',[id])).status,'paid')});
test('incorrect amount cannot mark order paid',async()=>{const id=randomUUID(),o=await place(id);await call('checkout_claim',[id]);await call('checkout_attach',[id,'testbill2']);await assert.rejects(()=>call('confirm_payment',[o.reference,'testbill2','invoice2',1]),/does not match/);assert.equal((await call('checkout_status',[id])).status,'pending')});
test('late payment is flagged for review without taking another customer’s stock',async()=>{const id=randomUUID(),o=await place(id);await call('checkout_claim',[id]);await call('checkout_attach',[id,'testbill3']);await db.query("update orders set expires_at=now()-interval '1 second' where request_id=$1",[id]);const stock=(await db.query("select stock from variants where id='barrel-charcoal'")).rows[0].stock;await call('confirm_payment',[o.reference,'testbill3','invoice3',9700]);assert.equal((await call('checkout_status',[id])).status,'review');assert.equal((await db.query("select stock from variants where id='barrel-charcoal'")).rows[0].stock,stock)});
test('anonymous caller cannot read orders or create orders directly',async()=>{await db.exec('set role anon');try{await assert.rejects(()=>db.query('select * from orders'),/permission denied/);await assert.rejects(()=>place(),/permission denied/);const cat=await call('shop_catalog');assert.equal(cat.variants.length,3)}finally{await db.exec('reset role')}});
test('non-admin cannot open dashboard',async()=>{await db.exec('set role authenticated');try{await assert.rejects(()=>call('admin_dashboard'),/Admin access required/)}finally{await db.exec('reset role')}});
test('two requests competing for the final unit cannot both reserve it',async()=>{await db.exec("update variants set stock=1 where id='barrel-slate'");const result=await Promise.allSettled([place(randomUUID(),[{variant_id:'barrel-slate',quantity:1}]),place(randomUUID(),[{variant_id:'barrel-slate',quantity:1}])]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.filter(r=>r.status==='rejected').length,1)});
test('database rate limit blocks the sixth request',async()=>{for(let i=0;i<5;i++)assert.equal(await call('order_rate_limit',['test-bucket']),true);assert.equal(await call('order_rate_limit',['test-bucket']),false)});
